import { createHash, randomUUID } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { createDatabase, closeDatabase } from "../../packages/database/src/index.ts";
import { createPrivateObjectStorage, createS3Client, ensurePrivateBucket } from "../../packages/storage/src/index.ts";

const databaseUrl = process.env.RESTORE_DRILL_SOURCE_DATABASE_URL;
const manifestPath = process.env.RESTORE_DRILL_MANIFEST_PATH;
if (!databaseUrl || !manifestPath) throw new Error("Restore drill source URL and manifest path are required.");
const database = createDatabase({ connectionString: databaseUrl, maxConnections: 2 });
const organizationId = randomUUID(), userId = randomUUID(), membershipId = randomUUID(), projectId = randomUUID(), trainingId = randomUUID(), participantId = randomUUID(), recoveryParticipantId = randomUUID(), templateId = randomUUID(), templateVersionId = randomUUID(), assetId = randomUUID(), certificateId = randomUUID(), recoveryCertificateId = randomUUID(), generationJobId = randomUUID(), recoveryJobId = randomUUID();
const assetBytes = Buffer.from("restore-drill-template-asset-v1", "utf8"); const pdfBytes = Buffer.from("%PDF-1.4\nrestore-drill-certificate\n%%EOF\n", "utf8");
const assetSha = createHash("sha256").update(assetBytes).digest("hex"); const pdfSha = createHash("sha256").update(pdfBytes).digest("hex");
const assetKey = `template-assets/${assetId}/asset.png`; const pdfKey = `certificates/${certificateId}/1.pdf`;
const client = createS3Client({ endpoint: process.env.SOURCE_S3_ENDPOINT!, region: "us-east-1", bucket: process.env.SOURCE_S3_BUCKET!, accessKeyId: process.env.SOURCE_S3_ACCESS_KEY!, secretAccessKey: process.env.SOURCE_S3_SECRET_KEY!, forcePathStyle: true });
const storage = createPrivateObjectStorage(client, process.env.SOURCE_S3_BUCKET!);
const issuedAt = new Date("2026-08-31T00:00:00.000Z");
try {
  await ensurePrivateBucket(client, process.env.SOURCE_S3_BUCKET!, true);
  await database.insertInto("users").values({ id: userId, email: `restore-drill-${userId}@example.invalid`, password_hash: "synthetic-not-a-password" }).execute();
  await database.insertInto("organizations").values({ id: organizationId, name: "Restore Drill Tenant" }).execute();
  await database.insertInto("organization_memberships").values({ id: membershipId, organization_id: organizationId, user_id: userId }).execute();
  await database.insertInto("projects").values({ id: projectId, organization_id: organizationId, name: "Restore Drill Project", slug: `restore-drill-${projectId}` }).execute();
  await database.insertInto("trainings").values({ id: trainingId, organization_id: organizationId, project_id: projectId, name: "Restore Drill Training", code: "RESTORE-DRILL" }).execute();
  await database.insertInto("participants").values({ id: participantId, organization_id: organizationId, display_name: "Synthetic Restore Recipient" }).execute();
  await database.insertInto("participants").values({ id: recoveryParticipantId, organization_id: organizationId, display_name: "Synthetic Pending Recipient" }).execute();
  await database.insertInto("training_participants").values({ organization_id: organizationId, training_id: trainingId, participant_id: participantId }).execute();
  await database.insertInto("training_participants").values({ organization_id: organizationId, training_id: trainingId, participant_id: recoveryParticipantId }).execute();
  await database.insertInto("certificate_templates").values({ id: templateId, organization_id: organizationId, name: "Restore Drill Template" }).execute();
  await database.insertInto("template_assets").values({ id: assetId, organization_id: organizationId, template_id: templateId, storage_key: assetKey, original_filename: "asset.png", content_sha256: Buffer.from(assetSha, "hex"), detected_mime_type: "image/png", size_bytes: String(assetBytes.byteLength), created_by_membership_id: membershipId }).execute();
  await database.insertInto("template_versions").values({ id: templateVersionId, organization_id: organizationId, template_id: templateId, version: 1, definition_json: { version: 1, elements: [] } }).execute();
  await database.insertInto("template_version_assets").values({ template_version_id: templateVersionId, asset_id: assetId, organization_id: organizationId, template_id: templateId }).execute();
  await database.updateTable("template_versions").set({ status: "PUBLISHED", published_at: issuedAt }).where("id", "=", templateVersionId).execute();
  await database.insertInto("jobs").values({ id: generationJobId, organization_id: organizationId, job_type: "CERTIFICATE_GENERATION", idempotency_key: `restore-drill-${generationJobId}`, requested_by_membership_id: membershipId, progress_total: 1 }).execute();
  await database.insertInto("certificate_generation_jobs").values({ job_id: generationJobId, organization_id: organizationId, training_id: trainingId, template_version_id: templateVersionId, selection_mode: "EXPLICIT", request_fingerprint: Buffer.alloc(32, 1), renderer_revision: "pdfkit-qrcode-v1" }).execute();
  await database.insertInto("certificates").values({ id: certificateId, organization_id: organizationId, training_id: trainingId, participant_id: participantId, template_version_id: templateVersionId, certificate_number: "RESTORE-DRILL-001", verification_key_kid: "restore-drill-historical-kid" }).execute();
  await database.insertInto("certificate_issuance_snapshots").values({ certificate_id: certificateId, organization_id: organizationId, recipient_display_name: "Synthetic Restore Recipient", project_name: "Restore Drill Project", training_name: "Restore Drill Training", training_code: "RESTORE-DRILL", issued_at: issuedAt }).execute();
  await database.updateTable("certificates").set({ status: "GENERATING" }).where("id", "=", certificateId).execute();
  await database.insertInto("certificate_generation_items").values({ organization_id: organizationId, job_id: generationJobId, certificate_id: certificateId, generation_revision: 1, status: "SUCCEEDED" }).execute();
  await database.updateTable("certificates").set({ status: "AVAILABLE", issued_at: issuedAt, pdf_storage_key: pdfKey, pdf_content_sha256: Buffer.from(pdfSha, "hex"), pdf_size_bytes: String(pdfBytes.byteLength), pdf_mime_type: "application/pdf" }).where("id", "=", certificateId).execute();
  await database.updateTable("jobs").set({ status: "SUCCEEDED", progress_completed: 1, completed_at: issuedAt, updated_at: issuedAt }).where("id", "=", generationJobId).execute();
  await database.insertInto("queue_outbox").values({ organization_id: organizationId, message_type: "CERTIFICATE_GENERATION", deduplication_key: `${generationJobId}-generate`, payload_json: { version: 1, job_id: generationJobId, organization_id: organizationId }, dispatched_at: issuedAt }).execute();
  await database.updateTable("certificates").set({ status: "REVOKED", revoked_at: issuedAt, revocation_reason: "RESTORE_DRILL" }).where("id", "=", certificateId).execute();
  await database.insertInto("audit_logs").values({ organization_id: organizationId, actor_user_id: userId, actor_membership_id: membershipId, action: "CERTIFICATE_REVOKED", resource_type: "CERTIFICATE", resource_id: certificateId, request_id: randomUUID(), metadata: { reason: "RESTORE_DRILL" } }).execute();
  await database.insertInto("storage_cleanup_outbox").values({ organization_id: organizationId, object_key: `orphaned/${randomUUID()}`, not_before: issuedAt }).execute();
  await database.insertInto("jobs").values({ id: recoveryJobId, organization_id: organizationId, job_type: "CERTIFICATE_GENERATION", idempotency_key: `restore-drill-recovery-${recoveryJobId}`, requested_by_membership_id: membershipId, progress_total: 1, queued_at: issuedAt, updated_at: issuedAt }).execute();
  await database.insertInto("certificate_generation_jobs").values({ job_id: recoveryJobId, organization_id: organizationId, training_id: trainingId, template_version_id: templateVersionId, selection_mode: "EXPLICIT", request_fingerprint: Buffer.alloc(32, 2), renderer_revision: "pdfkit-qrcode-v1" }).execute();
  await database.insertInto("certificates").values({ id: recoveryCertificateId, organization_id: organizationId, training_id: trainingId, participant_id: recoveryParticipantId, template_version_id: templateVersionId, certificate_number: "RESTORE-DRILL-PENDING-001", verification_key_kid: "restore-drill-historical-kid" }).execute();
  await database.insertInto("certificate_issuance_snapshots").values({ certificate_id: recoveryCertificateId, organization_id: organizationId, recipient_display_name: "Synthetic Pending Recipient", project_name: "Restore Drill Project", training_name: "Restore Drill Training", training_code: "RESTORE-DRILL", issued_at: issuedAt }).execute();
  await database.insertInto("certificate_generation_items").values({ organization_id: organizationId, job_id: recoveryJobId, certificate_id: recoveryCertificateId, generation_revision: 1, status: "PENDING", updated_at: issuedAt }).execute();
  await database.insertInto("queue_outbox").values({ organization_id: organizationId, message_type: "CERTIFICATE_GENERATION", deduplication_key: `${recoveryJobId}-generate`, payload_json: { version: 1, job_id: recoveryJobId, organization_id: organizationId }, dispatched_at: issuedAt }).execute();
  await storage.put({ key: assetKey, body: assetBytes, contentType: "image/png", contentSha256Hex: assetSha }); await storage.put({ key: pdfKey, body: pdfBytes, contentType: "application/pdf", contentSha256Hex: pdfSha });
  await writeFile(manifestPath, JSON.stringify({ organization_id: organizationId, participant_id: participantId, training_id: trainingId, certificate_id: certificateId, generation_job_id: generationJobId, recovery_job_id: recoveryJobId, template_version_id: templateVersionId, public_identifier: (await database.selectFrom("certificates").select("public_identifier").where("id", "=", certificateId).executeTakeFirstOrThrow()).public_identifier, verification_key_kid: "restore-drill-historical-kid", objects: [{ key: assetKey, sha256: assetSha, size_bytes: assetBytes.byteLength, mime_type: "image/png", kind: "template_asset" }, { key: pdfKey, sha256: pdfSha, size_bytes: pdfBytes.byteLength, mime_type: "application/pdf", kind: "certificate_pdf" }] }));
} finally { await closeDatabase(database); }
